baseurl = "http://uh16.diin.io/"
languageCode = "de-de"
title = "2. Umma hüsla Hackathon EXTENDED"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "↩"
theme = "uh"


[permalinks]
    post = "post/:slug"


[params]
    # Tell me who you are
    author = "Digitale Initiativen"
    bio = "Plattform für Digitale Initiativen"
    #location = "Earth"
    site_description = ""
    copyright  = "Plattform für Digitale Initiativen"
    avatar = "css/images/avatar.png"

    # Format dates with Go's time formatting
    date_format = "02.01.2006"

[[params.menu]]
    before = false
    label  = "#UH2016"
    link   = "/"

[[params.menu]]
    before = false
    label  = "Umma hüsla"
    link   = "ummahuesla/"

[[params.menu]]
    before = false
    label  = "Veranstaltungen"
    link   = "veranstaltungen/"

[[params.menu]]
    before = false
    label  = "IoT"
    link   = "iot/"

[[params.menu]]
    before = false
    label  = "Vision"
    link   = "vision/"

[[params.menu]]
    before = false
    label  = "Über uns"
    link   = "ueber/"

[[params.menu]]
    before  = false
    label   = "FAQ"
    link    = "faq/"

[[params.menu]]
    before = false
    label  = "Blog"
    link   = "post/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://twitter.com/DigitalInit"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# create automatically.
    github          = "digitaleinitiativen"
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "DigitalInit"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = false
    categories = false
    tags = false
    tag_cloud = false
    logo_sidebar = true
